kind: ModelTraining
id: reuters-classifier-id
spec:
  model:
    name: reuters-classifier
    version: 1.0
  toolchain: mlflow  # MLFlow training toolchain integration
  entrypoint: main
  workDir: mlflow/tensorflow/reuters_classifier # MLproject location (in GitHub)
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 4024m
      memory: 4024Mi
    requests:
      cpu: 2024m
      memory: 2024Mi
  vcsName: reuters-classifier-repo